#cloud-config
package_update: true
package_upgrade: true
packages:
  - curl
  - git
  - qemu-guest-agent
  - software-properties-common # Required for ansible
runcmd:
  - [systemctl, enable, --now, qemu-guest-agent.service]
ansible:
  package_name: ansible
  install_method: distro
  pull:
    url: "https://github.com/amnoth/ansible-test.git"
    playbook_name: dev-ubuntu.yaml
    connection: local
apt:
  sources:
    ansible-ubuntu-ppa:
      source: "ppa:ansible/ansible"
