---
- name: "Development Station"
  hosts: localhost
  connection: local
  tasks:
    - name: "Create ~/src directory"
      file:
        path: ~/src
        state: directory
        mode: 0755
      become: yes
      become_user: root
      become_method: sudo
    - name: "Neovim - Install prerequisites"
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - ninja-build
        - gettext
        - cmake
        - unzip
        - curl
      become: yes
      become_user: root
      become_method: sudo
    - name: "Neovim - Build stable release & install from deb package"
      shell: |
        git clone https://github.com/neovim/neovim
        cd neovim
        git checkout stable
        make CMAKE_BUILD_TYPE=RelWithDebInfo
        cd build
        cpack -G DEB && sudo dpkg -i nvim-linux64.deb
      args:
        chdir: ~/src
      become: yes
      become_user: root
      become_method: sudo
